<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-K6PT340" failures="1" tests="3" name="listener_ExtentReport.TestClass" time="0.462" errors="0" timestamp="2025-10-26T18:49:59 IST" skipped="1">
  <testcase classname="listener_ExtentReport.TestClass" name="testLogo" time="0.433"/>
  <system-out/>
  <testcase classname="listener_ExtentReport.TestClass" name="testURL" time="0.028">
    <failure message="expected [https://www.geeksforgeeks.org/software-testing/automation-testing-software-] but found [https://www.geeksforgeeks.org/software-testing/automation-testing-software-testing/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://www.geeksforgeeks.org/software-testing/automation-testing-software-] but found [https://www.geeksforgeeks.org/software-testing/automation-testing-software-testing/]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at listener_ExtentReport.TestClass.testURL(TestClass.java:56)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
]]>
    </failure>
  </testcase> <!-- testURL -->
  <system-out/>
  <testcase classname="listener_ExtentReport.TestClass" name="testSkip" time="0.001">
    <skipped/>
  </testcase> <!-- testSkip -->
  <system-out/>
</testsuite> <!-- listener_ExtentReport.TestClass -->
